#pragma once

#define IDI_ICON_APP 100

#define IDS_SETTINGS 200
#define IDS_EDIT_USER_PHRASES 201
#define IDS_EDIT_EXCLUDED_PHRASES 202
#define IDS_OPEN_USER_DATA_FOLDER 203
#define IDS_OPEN_LOG_FOLDER 204
#define IDS_ENABLE_LOGGING 205
#define IDS_TRACE_LOG 206
#define IDS_RESTART_SERVER 207
#define IDS_TRAY_TIP 208
#define IDS_DAEMON_STARTING 209
#define IDS_SERVER_RUNNING 210
#define IDS_STOP_SERVER 211

#define IDS_CURSOR_BETWEEN_SYLLABLES 300
#define IDS_SYLLABLES_REQUIRED 301
#define IDS_SYLLABLES_MAXIMUM 302
#define IDS_PHRASE_ALREADY_EXISTS 303
#define IDS_PRESS_ENTER_TO_ADD_THE_PHRASE 304
#define IDS_MARKING_NOT_AVAILABLE_IN_FONT_ANNOTATION_MODE 305
#define IDS_FONT_ANNOTATION_MODE_TOOLTIP 306
#define IDS_FONT_ANNOTATION_MODE_TOOLTIP_ADVANCED 307

#define IDS_BOOST 308
#define IDS_EXCLUDE 309
#define IDS_CANCEL 310
#define IDS_BOOST_PROMPT 311
#define IDS_EXCLUDE_PROMPT 312

#define IDS_USER_PHRASE_FILE_HEADER 400
#define IDS_EXCLUDED_PHRASE_FILE_HEADER 401

#define IDS_CHARACTER_INFORMATION 500
