#pragma once

#define IDI_ICON_APP 100
#define IDI_ICON_ZH 101
#define IDI_ICON_EN 102

#define IDS_SWITCH_TO_ENGLISH 200
#define IDS_SWITCH_TO_CHINESE 201
#define IDS_OUTPUT_SIMPLIFIED 202
#define IDS_OUTPUT_TRADITIONAL 203
#define IDS_PUNCTUATION_HALF 204
#define IDS_PUNCTUATION_FULL 205
#define IDS_ENABLE_ASSOCIATED_PHRASES 206
#define IDS_ENABLE_BOPOMOFO_ANNOTATION 207
#define IDS_SETTINGS 208
#define IDS_EDIT_USER_PHRASES 209
#define IDS_EDIT_EXCLUDED_PHRASES 210
#define IDS_OPEN_USER_DATA_FOLDER 211
#define IDS_IME_MODE_TOOLTIP 212
#define IDS_WIN_MCBOPOMOFO 213
